// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxDBAggregator) DeepCopyInto(out *InfluxDBAggregator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxDBAggregator.
func (in *InfluxDBAggregator) DeepCopy() *InfluxDBAggregator {
	if in == nil {
		return nil
	}
	out := new(InfluxDBAggregator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfluxDBAggregator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxDBAggregatorList) DeepCopyInto(out *InfluxDBAggregatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfluxDBAggregator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxDBAggregatorList.
func (in *InfluxDBAggregatorList) DeepCopy() *InfluxDBAggregatorList {
	if in == nil {
		return nil
	}
	out := new(InfluxDBAggregatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfluxDBAggregatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxDBAggregatorSpec) DeepCopyInto(out *InfluxDBAggregatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxDBAggregatorSpec.
func (in *InfluxDBAggregatorSpec) DeepCopy() *InfluxDBAggregatorSpec {
	if in == nil {
		return nil
	}
	out := new(InfluxDBAggregatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxDBAggregatorStatus) DeepCopyInto(out *InfluxDBAggregatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxDBAggregatorStatus.
func (in *InfluxDBAggregatorStatus) DeepCopy() *InfluxDBAggregatorStatus {
	if in == nil {
		return nil
	}
	out := new(InfluxDBAggregatorStatus)
	in.DeepCopyInto(out)
	return out
}
