kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influxdb-aggregator
subjects:
- kind: ServiceAccount
  name: influxdb-aggregator
roleRef:
  kind: Role
  name: influxdb-aggregator
  apiGroup: rbac.authorization.k8s.io
